# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from client.transport import dfl_pb2 as dfl__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dfl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeerServiceStub(object):
    """Service exposed by every Jetson peer
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExchangeMeta = channel.unary_unary(
                '/dfl.PeerService/ExchangeMeta',
                request_serializer=dfl__pb2.MetaRequest.SerializeToString,
                response_deserializer=dfl__pb2.MetaResponse.FromString,
                _registered_method=True)
        self.PushModel = channel.unary_unary(
                '/dfl.PeerService/PushModel',
                request_serializer=dfl__pb2.ModelPayload.SerializeToString,
                response_deserializer=dfl__pb2.Ack.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/dfl.PeerService/Ping',
                request_serializer=dfl__pb2.PingRequest.SerializeToString,
                response_deserializer=dfl__pb2.PingResponse.FromString,
                _registered_method=True)


class PeerServiceServicer(object):
    """Service exposed by every Jetson peer
    """

    def ExchangeMeta(self, request, context):
        """Exchange metadata (loss history, label distribution) for knowledge gain evaluation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushModel(self, request, context):
        """Push model state_dict to a peer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check / peer discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExchangeMeta': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeMeta,
                    request_deserializer=dfl__pb2.MetaRequest.FromString,
                    response_serializer=dfl__pb2.MetaResponse.SerializeToString,
            ),
            'PushModel': grpc.unary_unary_rpc_method_handler(
                    servicer.PushModel,
                    request_deserializer=dfl__pb2.ModelPayload.FromString,
                    response_serializer=dfl__pb2.Ack.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=dfl__pb2.PingRequest.FromString,
                    response_serializer=dfl__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dfl.PeerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dfl.PeerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeerService(object):
    """Service exposed by every Jetson peer
    """

    @staticmethod
    def ExchangeMeta(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfl.PeerService/ExchangeMeta',
            dfl__pb2.MetaRequest.SerializeToString,
            dfl__pb2.MetaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfl.PeerService/PushModel',
            dfl__pb2.ModelPayload.SerializeToString,
            dfl__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dfl.PeerService/Ping',
            dfl__pb2.PingRequest.SerializeToString,
            dfl__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
