# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dfl.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'dfl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdfl.proto\x12\x03\x64\x66l\"5\n\x0bPingRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x13\n\x0bsender_addr\x18\x02 \x01(\t\"2\n\x0cPingResponse\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x11\n\tis_active\x18\x02 \x01(\x08\" \n\x0bMetaRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\"\x86\x01\n\x0cMetaResponse\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\x11\n\tloss_prev\x18\x02 \x01(\x02\x12\x14\n\x0closs_current\x18\x03 \x01(\x02\x12\x12\n\nlabel_dist\x18\x04 \x03(\x02\x12\x15\n\rcpu_frequency\x18\x05 \x01(\x02\x12\x11\n\tidle_time\x18\x06 \x01(\x02\"G\n\x0bTensorProto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x03\x12\r\n\x05\x64type\x18\x04 \x01(\t\"Z\n\x0cModelPayload\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12!\n\x07tensors\x18\x02 \x03(\x0b\x32\x10.dfl.TensorProto\x12\x14\n\x0closs_current\x18\x03 \x01(\x02\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x99\x01\n\x0bPeerService\x12\x33\n\x0c\x45xchangeMeta\x12\x10.dfl.MetaRequest\x1a\x11.dfl.MetaResponse\x12(\n\tPushModel\x12\x11.dfl.ModelPayload\x1a\x08.dfl.Ack\x12+\n\x04Ping\x12\x10.dfl.PingRequest\x1a\x11.dfl.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=18
  _globals['_PINGREQUEST']._serialized_end=71
  _globals['_PINGRESPONSE']._serialized_start=73
  _globals['_PINGRESPONSE']._serialized_end=123
  _globals['_METAREQUEST']._serialized_start=125
  _globals['_METAREQUEST']._serialized_end=157
  _globals['_METARESPONSE']._serialized_start=160
  _globals['_METARESPONSE']._serialized_end=294
  _globals['_TENSORPROTO']._serialized_start=296
  _globals['_TENSORPROTO']._serialized_end=367
  _globals['_MODELPAYLOAD']._serialized_start=369
  _globals['_MODELPAYLOAD']._serialized_end=459
  _globals['_ACK']._serialized_start=461
  _globals['_ACK']._serialized_end=500
  _globals['_PEERSERVICE']._serialized_start=503
  _globals['_PEERSERVICE']._serialized_end=656
# @@protoc_insertion_point(module_scope)
