"""
GrpcTransport: Physical P2P transport layer for DFL on Jetson Orin Nanos.

This module replaces the simulator's in-memory client list with real gRPC
calls over the 192.168.38.x subnet. Each Jetson runs a gRPC server that:
  1. Responds to Ping (peer discovery)
  2. Serves metadata (loss history, label distribution) for knowledge gain
  3. Accepts pushed model state_dicts asynchronously
"""

import io
import logging
import threading
import time
from collections import OrderedDict
from concurrent import futures
from typing import Callable, Dict, List, Optional, Tuple

import grpc
import numpy as np
import torch

# These are generated by compile_protos.sh — see README
from client.transport import dfl_pb2
from client.transport import dfl_pb2_grpc

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Serialization helpers
# ---------------------------------------------------------------------------

def state_dict_to_protos(state_dict: Dict[str, torch.Tensor]) -> List[dfl_pb2.TensorProto]:
    """Serialize a PyTorch state_dict into a list of TensorProto messages."""
    protos = []
    for name, tensor in state_dict.items():
        buf = io.BytesIO()
        # Use numpy for compact serialization (avoids pickle overhead)
        np.save(buf, tensor.cpu().detach().numpy())
        protos.append(dfl_pb2.TensorProto(
            name=name,
            data=buf.getvalue(),
            shape=list(tensor.shape),
            dtype=str(tensor.dtype),
        ))
    return protos


def protos_to_state_dict(protos: List[dfl_pb2.TensorProto]) -> OrderedDict:
    """Deserialize TensorProto messages back into a PyTorch state_dict."""
    state_dict = OrderedDict()
    for tp in protos:
        buf = io.BytesIO(tp.data)
        arr = np.load(buf, allow_pickle=False)
        state_dict[tp.name] = torch.from_numpy(arr)
    return state_dict


# ---------------------------------------------------------------------------
# gRPC Servicer (runs on each Jetson)
# ---------------------------------------------------------------------------

class PeerServicer(dfl_pb2_grpc.PeerServiceServicer):
    """
    gRPC server-side handler. One instance per Jetson.
    Callbacks are injected by PhysicalClient so the servicer can read
    live client state (model, loss, label_dist, etc.).
    """

    def __init__(
        self,
        node_id: str,
        get_meta_cb: Callable,
        on_model_received_cb: Callable,
        is_active_cb: Callable,
    ):
        self.node_id = node_id
        self._get_meta = get_meta_cb
        self._on_model_received = on_model_received_cb
        self._is_active = is_active_cb
        # Thread-safe buffer for received models
        self._received_models: List[Tuple[str, OrderedDict, float]] = []
        self._lock = threading.Lock()

    def Ping(self, request, context):
        logger.info(f"[{self.node_id}] Ping from {request.sender_id}")
        return dfl_pb2.PingResponse(
            peer_id=self.node_id,
            is_active=self._is_active(),
        )

    def ExchangeMeta(self, request, context):
        meta = self._get_meta()
        return dfl_pb2.MetaResponse(
            peer_id=self.node_id,
            loss_prev=meta["loss_prev"],
            loss_current=meta["loss_current"],
            label_dist=meta["label_dist"],
            cpu_frequency=meta["cpu_frequency"],
            idle_time=meta["idle_time"],
        )

    def PushModel(self, request, context):
        try:
            sd = protos_to_state_dict(request.tensors)
            with self._lock:
                self._received_models.append(
                    (request.sender_id, sd, request.loss_current)
                )
            logger.info(
                f"[{self.node_id}] Received model from {request.sender_id} "
                f"(loss={request.loss_current:.4f})"
            )
            self._on_model_received(request.sender_id, sd, request.loss_current)
            return dfl_pb2.Ack(success=True, message="OK")
        except Exception as e:
            logger.error(f"[{self.node_id}] PushModel error: {e}")
            return dfl_pb2.Ack(success=False, message=str(e))

    def drain_received_models(self) -> List[Tuple[str, OrderedDict, float]]:
        """Pop all buffered models (called by the training loop between rounds)."""
        with self._lock:
            models = list(self._received_models)
            self._received_models.clear()
        return models


# ---------------------------------------------------------------------------
# GrpcTransport: high-level API used by PhysicalClient
# ---------------------------------------------------------------------------

class GrpcTransport:
    """
    Manages the gRPC server + outbound client stubs for one Jetson node.

    Usage:
        transport = GrpcTransport(
            node_id="jetson1",
            listen_addr="0.0.0.0:50051",
            peer_addrs={"jetson2": "192.168.38.209:50051"},
            get_meta_cb=..., on_model_received_cb=..., is_active_cb=...
        )
        transport.start()
        ...
        transport.stop()
    """

    def __init__(
        self,
        node_id: str,
        listen_addr: str,
        peer_addrs: Dict[str, str],
        get_meta_cb: Callable,
        on_model_received_cb: Callable,
        is_active_cb: Callable,
        max_workers: int = 4,
    ):
        self.node_id = node_id
        self.listen_addr = listen_addr
        self.peer_addrs = peer_addrs  # {peer_id: "ip:port"}

        self.servicer = PeerServicer(
            node_id, get_meta_cb, on_model_received_cb, is_active_cb
        )
        self.server = grpc.server(
            futures.ThreadPoolExecutor(max_workers=max_workers),
            options=[
                ("grpc.max_send_message_length", 256 * 1024 * 1024),
                ("grpc.max_receive_message_length", 256 * 1024 * 1024),
            ],
        )
        dfl_pb2_grpc.add_PeerServiceServicer_to_server(self.servicer, self.server)
        self.server.add_insecure_port(self.listen_addr)

        # Lazy-init stubs
        self._channels: Dict[str, grpc.Channel] = {}
        self._stubs: Dict[str, dfl_pb2_grpc.PeerServiceStub] = {}

    def start(self):
        self.server.start()
        logger.info(f"[{self.node_id}] gRPC server listening on {self.listen_addr}")

    def stop(self, grace: float = 2.0):
        self.server.stop(grace)
        for ch in self._channels.values():
            ch.close()
        logger.info(f"[{self.node_id}] gRPC server stopped")

    def _get_stub(self, peer_id: str) -> dfl_pb2_grpc.PeerServiceStub:
        if peer_id not in self._stubs:
            addr = self.peer_addrs[peer_id]
            ch = grpc.insecure_channel(
                addr,
                options=[
                    ("grpc.max_send_message_length", 256 * 1024 * 1024),
                    ("grpc.max_receive_message_length", 256 * 1024 * 1024),
                ],
            )
            self._channels[peer_id] = ch
            self._stubs[peer_id] = dfl_pb2_grpc.PeerServiceStub(ch)
        return self._stubs[peer_id]

    # ------------------------------------------------------------------
    # Outbound RPCs
    # ------------------------------------------------------------------

    def ping_peer(self, peer_id: str, timeout: float = 5.0) -> Optional[dfl_pb2.PingResponse]:
        """Check if a peer is reachable and active."""
        try:
            stub = self._get_stub(peer_id)
            resp = stub.Ping(
                dfl_pb2.PingRequest(sender_id=self.node_id, sender_addr=self.listen_addr),
                timeout=timeout,
            )
            return resp
        except grpc.RpcError as e:
            logger.warning(f"[{self.node_id}] Ping to {peer_id} failed: {e.code()}")
            return None

    def fetch_meta(self, peer_id: str, timeout: float = 10.0) -> Optional[dict]:
        """Fetch metadata from a peer for knowledge gain computation."""
        try:
            stub = self._get_stub(peer_id)
            resp = stub.ExchangeMeta(
                dfl_pb2.MetaRequest(sender_id=self.node_id),
                timeout=timeout,
            )
            return {
                "peer_id": resp.peer_id,
                "loss_prev": resp.loss_prev,
                "loss_current": resp.loss_current,
                "label_dist": list(resp.label_dist),
                "cpu_frequency": resp.cpu_frequency,
                "idle_time": resp.idle_time,
            }
        except grpc.RpcError as e:
            logger.warning(f"[{self.node_id}] ExchangeMeta with {peer_id} failed: {e.code()}")
            return None

    def push_model(
        self, peer_id: str, state_dict: Dict[str, torch.Tensor], loss: float, timeout: float = 60.0
    ) -> bool:
        """Push local model weights to a peer."""
        try:
            stub = self._get_stub(peer_id)
            payload = dfl_pb2.ModelPayload(
                sender_id=self.node_id,
                tensors=state_dict_to_protos(state_dict),
                loss_current=loss,
            )
            resp = stub.PushModel(payload, timeout=timeout)
            if resp.success:
                logger.info(f"[{self.node_id}] Pushed model to {peer_id}")
            else:
                logger.warning(f"[{self.node_id}] PushModel to {peer_id} rejected: {resp.message}")
            return resp.success
        except grpc.RpcError as e:
            logger.error(f"[{self.node_id}] PushModel to {peer_id} failed: {e.code()}")
            return False

    def discover_active_peers(self) -> List[str]:
        """Ping all known peers, return list of active peer IDs."""
        active = []
        for pid in self.peer_addrs:
            resp = self.ping_peer(pid)
            if resp and resp.is_active:
                active.append(pid)
        return active

    def drain_received_models(self):
        """Drain the inbound model buffer."""
        return self.servicer.drain_received_models()
